version: "2.4"
services:
  postgres:
    image: postgres:15
    mem_limit: 1024m
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/ale/Desktop/postgres-arqui-2:/var/lib/postgresql/data
    networks:
      - ale-network
  currency-converter:
    image: currency:2.9.5
    restart: always
    mem_limit: 512m
    ports:
      - "8008:8008"
    environment:
      URL: ${POSTGRES_URL}
      API_KEY: ${API_KEY}
    depends_on:
      - postgres
    networks:
      - ale-network
  angular:
    image: angular-software:3.5.1-docker
    ports:
      - "4200:80"
    volumes:
      - /home/ale/Documents/ArquitecturaSoftware/currency-converter/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - ale-network
networks:
  ale-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16
          gateway: 172.15.0.1