api:
  key: v4uy0dBrehQBvz7fDuf7bpw44AUxkfHU
  url: "https://api.apilayer.com/exchangerates_data/convert"

server:
  port: 8008

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/software
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter